### PR TITLE
Cleanup and reorder Dovecot config file template

### PR DESCRIPTION
**Pull request by figarocorso**
I have not tested this PR, please review and wait until anyone have tested it.

* Quota plugin is enabled at top level
* Config settings reordered beneath isolated sections

The diff is not very useful here, so the file: https://github.com/Zentyal/zinc-puppet/blob/c778c830e2284e3fe6a3a4779caeacec4f397284/modules/zentyalcloud/templates/mta/dovecot.conf.erb

### CODE REVIEW

**Comment by exekias** [comment]
LGTM when you put an entry in CHANGES.md, agree on testing before merging

**Comment by figarocorso** [comment]
I didn't add the CHANGES.md entry on purpose.

**Comment by exekias** [comment]
And why? I mean you can put it as a changed: reorganize dovecot conf or whatever. So we all know that there were some changes there. In theory it's ok, but if something happens we have a clue of a change

**Comment by exekias** [comment]
LGTM, agree on wait for QA

**Pull request merged**
